name: up_todo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#----------------- PACKAGES ---------------- #
dependencies:
  flutter:
    sdk: flutter

  # UTILITY PACKAGES #
  flutter_native_splash: ^2.4.1
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^2.0.0
  uuid: ^4.5.0
  # cupertino_calendar_picker: ^2.0.0+1


  # ICONS #
  cupertino_icons: ^1.0.6
  iconsax_plus: ^1.0.0
  iconsax: ^0.0.8

  # FIREBASE #
  firebase_core: ^3.4.1

  # AUTHENICATION #
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1


  # STATE MANAGEMENT #
  flutter_riverpod: ^2.5.1 # Main State Management
  get: ^4.6.6

  # I want to migrate to a different storage solution as well
  # Maybe [SqLite], [Hive], [Moor], [Shared Preferences]
  # LOCAL STORAGE
  shared_preferences: ^2.3.2 

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

  # Routing / Navigation
  go_router: ^14.2.7

  # PRODUCT SPECIFIC #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # LOCAL STORAGE
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS ---------------- #
  assets:
    - assets/logos/
    - assets/images/on_boarding/
    - assets/google_fonts/
    - assets/images/randoms/


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
