// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9V-vJzQrdhzEKFGT-BqXDBtr4hPj5chg',
    appId: '1:820357740832:android:1215799c716dad8b75bf45',
    messagingSenderId: '820357740832',
    projectId: 'uptodo-db155',
    storageBucket: 'uptodo-db155.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaI73mqlOFKfmcfOBexpKiJ386a1qlifg',
    appId: '1:820357740832:ios:be3664560a0bfdeb75bf45',
    messagingSenderId: '820357740832',
    projectId: 'uptodo-db155',
    storageBucket: 'uptodo-db155.appspot.com',
    androidClientId: '820357740832-gb60v8hmur92qlngsj6jm64fejvvrc6f.apps.googleusercontent.com',
    iosClientId: '820357740832-io8ctka8ka5s1tn6semafr0absk7meem.apps.googleusercontent.com',
    iosBundleId: 'com.example.upTodo',
  );

}